<?php
	$DBN = 'unicorn';
	$UNAME = 'unicorn';
	$UPASS = 'unicorn';
	
	$WELCOME_HTML_SYMBOL = '#_WELCOME_HTML_#';
	
	$TELE_PROD_HTML_SYMBOL = '#_TELE_PROD_HTML_#';
	$TELE_PROD_DETAIL_HTML_SYMBOL = '#_TELE_PROD_DETAIL_HTML_#';
	
	$UNICORN_EVENT_HTML_SYMBOL = '#_UNICORN_EVENT_HTML_#';
	$UNICORN_EVENT_DETAIL_HTML_SYMBOL = '#_UNICORN_EVENT_DETAIL_HTML_#';
	
	$WE_ARE_HTML_SYMBOL = '#_WE_ARE_HTML_#';
	
	$AVENUES_HTML_SYMBOL = '#_AVENUES_HTML_#';
	
	$CLIENT_LIST_HTML_SYMBOL = '#_CLIENT_LIST_HTML_#';
	
	$REACH_US_HTML_SYMBOL = '#_REACH_US_HTML_#';
	
	$BASE_DIR = '/var/www_fu/';
	$UPL_IMG_DIR = $BASE_DIR.'admin/upl_images/';
	
	$IMG_URL = 'http://'.$_SERVER['HTTP_HOST'].'/img.x?fnqx=';
	
	// Display properties
	$IMG_VIEW_MAX_W=200;
	$IMG_VIEW_MAX_H=200;

?>